export const ORDER_STATUS_PENDING = "PENDING";
export const ORDER_STATUS_CONFORMED = "CONFORMED";
export const ORDER_STATUS_SHIPPED = "SHIPPED";
export const ORDER_STATUS_DELIVERED = "DELIVERED";
export const ORDER_STATUS_CANCELLED = "CANCELLED";
