export const ORDER_STSTUS_PENDING = "PENDING";
export const ORDER_STSTUS_CONFORMED = "CONFORMED";
export const ORDER_STSTUS_SHIPPED = "SHIPPED";
export const ORDER_STSTUS_DELIVERED = "DELIVERED";
export const ORDER_STSTUS_CANCELLED = "CANCELLED";
